name: Python CI

on:
  push:
    branches:
      - main  # Quando houver push no branch main
  pull_request:
    branches:
      - main  # Quando houver um pull request para o branch main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use a versão do Python que seu projeto requer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover backend/tests  # Isso vai rodar seus testes na pasta backend/tests
